### ISSUE TITLE
发现一个严重的安全问题

### ISSUE THREAD

**Issue by jacksonlingda** [65487123/zprpc#1]
大佬，我看你这个项目引用了com.fasterxml.jackson.core:jackson-databind@2.9.8组件，存在一个严重漏洞，建议你升级下。
```
漏洞描述：
FasterXML jackson-databind是一个基于JAVA可以将XML和JSON等数据格式与JAVA对象进行转换的库。Jackson可以轻松的将Java对象转换成json对象和xml文档，同样也可以将json、xml转换成Java对象。
FasterXML jackson-databind 2.x版本至2.9.10.8版本存在代码问题漏洞，该漏洞源于错误地处理了序列化小工具和类型之间的交互，涉及到com.oracle.wls.shaded.org.apache.xalan.lib.sql.JNDIConnectionPool (aka embedded Xalan in org.glassfish.web/javax.servlet.jsp.jstl)。
漏洞级别：高危
影响范围：[2.0.0, 2.9.10.8)
最小修复版本：2.9.10.8
引入路径：
com.lzp.zprpc:zprpc-parent:1.1->com.lzp.zprpc:rpc-artifacts@1.1->com.lzp.zprpc:rpc-client@1.1->com.lzp.zprpc:rpc-registry@1.1->com.alibaba.nacos:nacos-client@1.3.1->com.fasterxml.jackson.core:jackson-databind@2.9.8
```
除此之外还有21个严重的漏洞，我用这个工具测的，https://www.murphysec.com/j?p=befaf5

**Comment by 65487123** [comment]
> 大佬，我看你这个项目引用了com.fasterxml.jackson.core:jackson-databind@2.9.8组件，存在一个严重漏洞，建议你升级下。
> 
> ```
> 漏洞描述：
> FasterXML jackson-databind是一个基于JAVA可以将XML和JSON等数据格式与JAVA对象进行转换的库。Jackson可以轻松的将Java对象转换成json对象和xml文档，同样也可以将json、xml转换成Java对象。
> FasterXML jackson-databind 2.x版本至2.9.10.8版本存在代码问题漏洞，该漏洞源于错误地处理了序列化小工具和类型之间的交互，涉及到com.oracle.wls.shaded.org.apache.xalan.lib.sql.JNDIConnectionPool (aka embedded Xalan in org.glassfish.web/javax.servlet.jsp.jstl)。
> 漏洞级别：高危
> 影响范围：[2.0.0, 2.9.10.8)
> 最小修复版本：2.9.10.8
> 引入路径：
> com.lzp.zprpc:zprpc-parent:1.1->com.lzp.zprpc:rpc-artifacts@1.1->com.lzp.zprpc:rpc-client@1.1->com.lzp.zprpc:rpc-registry@1.1->com.alibaba.nacos:nacos-client@1.3.1->com.fasterxml.jackson.core:jackson-databind@2.9.8
> ```
> 
> 除此之外还有21个严重的漏洞，我用这个工具测的，https://www.murphysec.com/j?p=befaf5

谢谢你的提醒。
我看了下，我这项目中没有用到这个包提供的功能，只是在依赖nacos-client时间接依赖了这个包。还有就是两个demo工程，由于是基于springboot，也间接依赖了这个包。 
现在已经把这个包都给排除了， git仓库已更新。

**Comment by 65487123** [comment]
> 大佬，我看你这个项目引用了com.fasterxml.jackson.core:jackson-databind@2.9.8组件，存在一个严重漏洞，建议你升级下。
> 
> ```
> 漏洞描述：
> FasterXML jackson-databind是一个基于JAVA可以将XML和JSON等数据格式与JAVA对象进行转换的库。Jackson可以轻松的将Java对象转换成json对象和xml文档，同样也可以将json、xml转换成Java对象。
> FasterXML jackson-databind 2.x版本至2.9.10.8版本存在代码问题漏洞，该漏洞源于错误地处理了序列化小工具和类型之间的交互，涉及到com.oracle.wls.shaded.org.apache.xalan.lib.sql.JNDIConnectionPool (aka embedded Xalan in org.glassfish.web/javax.servlet.jsp.jstl)。
> 漏洞级别：高危
> 影响范围：[2.0.0, 2.9.10.8)
> 最小修复版本：2.9.10.8
> 引入路径：
> com.lzp.zprpc:zprpc-parent:1.1->com.lzp.zprpc:rpc-artifacts@1.1->com.lzp.zprpc:rpc-client@1.1->com.lzp.zprpc:rpc-registry@1.1->com.alibaba.nacos:nacos-client@1.3.1->com.fasterxml.jackson.core:jackson-databind@2.9.8
> ```
> 
> 除此之外还有21个严重的漏洞，我用这个工具测的，https://www.murphysec.com/j?p=befaf5

不好意思，我又看了下，发现我用的这个nacos-client，在初始化nameservice时还是会去找这个包的，那我还是把这个包的版本升一下吧。
